- name: Copy the ansible-container related files to the remote machine
  copy:
    src: "{{ app }}/"
    dest: "~/workspace/{{ app }}/"
- name: Enusre the docker image is the latest - {{ app }}
  docker_image:
    name: "{{ image }}"
    force: yes
- name: Build the docker container contains the {{ app }}
  shell: ansible-container build --no-container-cache
  args:
    chdir: "~/workspace/{{ app }}"
- name: Post-action for the mount folders
  file:
    path: "~/workspace/{{ app }}/{{ item }}" 
    state: directory
    mode: 0777
    owner: vagrant
    group: vagrant
  loop: "{{ items }}"
- name: Stop the running containers
  shell: ansible-container stop
  args:
    chdir: "~/workspace/{{ app }}"
- name: Start the docker container contains the {{ app }}
  shell: ansible-container run
  args:
    chdir: "~/workspace/{{ app }}"
