Vagrant.configure("2") do |config|
    # do something
    config.vm.box = "ubuntu/trusty64"
    config.vm.provider "virtualbox" do |vb|
        vb.name = "mission1"
        vb.customize ["modifyvm", :id, "--cpuexecutioncap", "70"]
        vb.memory = 2048
        vb.cpus = 2
    end
    # Nginx
    config.vm.network "forwarded_port", guest: 8888, host: 8888
    # Jenkins web
    config.vm.network "forwarded_port", guest: 8080, host: 8080
    # Gogs web
    config.vm.network "forwarded_port", guest: 10080, host: 10080
    # Gogs ssh
    config.vm.network "forwarded_port", guest: 10022, host: 10022
    # Jenkins agent
    config.vm.network "forwarded_port", guest: 50000, host: 50000
    config.ssh.keep_alive = true
    config.vm.provision "shell",
        inline: "mkdir ~/workspace && sudo apt-get install -y linux-headers-$(uname -r) build-essential dkms"
    # The below mount point will caused the containers in the VM could not change the permission for files/folders,
    # because the permission controlled by the VM-host
    config.vm.synced_folder "data/", "/home/vagrant/workspace", disabled: true
end
