Vagrant.configure("2") do |config|
    # do something
    config.vm.box = "ubuntu/trusty64"
    config.vm.provider "virtualbox" do |vb|
        vb.name = "mission1"
        vb.customize ["modifyvm", :id, "--cpuexecutioncap", "70"]
        vb.memory = 2048
        vb.cpus = 2
    end
    config.vm.network "forwarded_port", guest: 8080, host: 8080
    config.vm.network "forwarded_port", guest: 10080, host: 10080
    config.vm.network "forwarded_port", guest: 10022, host: 10022
    config.vm.network "forwarded_port", guest: 50000, host: 50000
    config.vm.network "forwarded_port", guest: 80, host: 80
    config.ssh.keep_alive = true
    config.vm.provision "shell",
        inline: "sudo apt-get install -y linux-headers-$(uname -r) build-essential dkms"
    config.vm.synced_folder "data/", "/home/vagrant/workspace"
end
