---
- hosts: default
  tasks:
  - name: Install Nginx
    become: yes
    package: 
      name: nginx
      state: present
  - name: Install Docker
    become: yes
    shell: curl -fsSL get.docker.com -o get-docker.sh && bash get-docker.sh
  - name: Install docker-compose
    become: yes
    shell: curl -L https://github.com/docker/compose/releases/download/1.21.2/docker-compose-$(uname -s)-$(uname -m) -o /usr/local/bin/docker-compose && chmod +x /usr/local/bin/docker-compose
  - name: Grant permission for vagrant to run docker command
    become: yes
    user:
      name=vagrant
      state=present
      append=yes
      groups=docker
