---
- hosts: default
  tasks:
    - include: common/prepare_ansible-container.yml
    - include: common/start_app_with_docker.yml app=Gogs images=["gogs/gogs:latest","mysql:5.7"] subfolders=["data","mysql_data"]
