---
- hosts: default
  tasks:
    - include: common/prepare_ansible-container.yml
    - include: common/start_app_with_docker.yml app=Jenkins images=["jenkins/jenkins:lts"] subfolders=["data"]
    - name: Wait 120 sec for the Jenkins Master start
      wait_for:
        port: 8080
        delay: 30
        timeout: 300
    - name: Download the slave.jar
      get_url:
        url: http://localhost:8080/jnlpJars/slave.jar
        dest: ~/workspace/Jenkins
    - name: Install java runtime
      become: true
      apt:
        name: default-jre
        state: present
    - name: Laungh the Jenkins slave
      shell: java -jar slave.jar -jnlpUrl http://localhost:8080/computer/Host/slave-agent.jnlp -secret e0103d112c3a50519e553a523a39ec67a2ea79bd904c400472c6118520086747
